# Generated by Django 5.1.7 on 2025-03-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracttemplate",
            name="variables",
            field=models.JSONField(default=list, editable=False),
        ),
    ]
