# Generated by Django 5.1.7 on 2025-03-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_contracttemplate_variables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracttemplate",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
